name: continuous-deploy

on:
  push:
    branches:
      - 'master' 

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run start
      - name: Trigger Re-Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'http://mickhat.xyz:60010/cgi-bin/redeploy?type=flo-bot&authorization=${{ secrets.authorization }}'
          method: 'GET'
