name: continuous-deploy

on:
  push:
    branches:
      - 'master' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Trigger Re-Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'http://mickhat.xyz:60030/cgi-bin/redeploy?type=flo-bot'
          method: 'GET'
